name: SIGNAL daily report

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build and push report
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: a7ebd591bd69d8a1bd777a60ab7ce089
        run: python build_signal.py
